'use strict'
const navegationBar = document.querySelector('.nav');

const navContainer = document.querySelector('.nav-ul')
const intro = document.querySelector('.intro');
const aboutUsContent = document.querySelector('.about-content');
const contactBox = document.querySelector('.contact-overlay');
const closeContactButton = document.querySelector('.close-button')
const footer = document.querySelector('.footer-content')
const ourPeopleBtnBox = document.querySelector('.ourpeople--btn-box');
const peopleNav = document.querySelector('.people-navigation');
const nextPrevBtns = document.querySelector('.buttons-container');
const main = document.querySelectorAll('main');
const navLinks = document.querySelectorAll('header nav a')
const sebas = {
    worker: 'Sebastian Enrique Leupold',
    func: 'CEO',
    img: '/Sebas.0130d094.png',
    workingIn: 'Liberty America',
    graduationInfo: 'Electronic Engenier at  UTN',
    experiences: 'X (1997-2008), X (1803-3605)'

}
const guille = {
    worker: 'Guillermo Gerardo Leupold',
    func: 'CFO',
    img: '/Guille.ab694ac3.png',
    workingIn: 'Sanofi latam',
    graduationInfo: 'Busines Administration UB',
    experiences: 'X (1997-2008), X (1803-3605)'
}
const roli = {
    worker: 'Rodolfo Javier Leupold',
    func: 'COO',
    img: '/Roli.b685959f.png',
    workingIn: 'X latam',
    graduationInfo: 'Busines Administration UBA',
    experiences: 'X (1997-2008), X (1803-3605)'
}
const ceoButton = document.getElementById('btn-CEO');
const cfoButton = document.getElementById('btn-CFO');
const overlay = document.querySelector('.contact-overlay')

const text1 = `
    In 3fi solutions we work in bla bla bla... bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...
    bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...
    bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...
    bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...
    bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...
    bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...
    bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...
    bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...
    bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...
    bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...
    bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...
`
const text2 = `In the market, we try to develop bla bla bla... bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...
bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...
bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...
bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...
bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...
bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...
bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...
bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...
bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...
bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...
bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...`

const text3 = `Finally, about our present and our futurebla bla bla... bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...
bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...
bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...
bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...
bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...
bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...
bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...
bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...
bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...
bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...
bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla...bla bla bla... `
const img1 = `/graph1.b492c23a.png` ///graph1.fa33cb58.png
const img2 = `/graph2.092c49a3.png` //graph2.b981ea2b.png

const [prev, next] = document.querySelectorAll('.button-change');
const dotsArr = document.querySelector('.dots-carrousel');
const dot1 = document.querySelector('.dot-1').lastElementChild
const dot2 = document.querySelector('.dot-2').lastElementChild
const dot3 = document.querySelector('.dot-3').lastElementChild


export {
    navegationBar, navContainer, intro, aboutUsContent, contactBox, closeContactButton, ourPeopleBtnBox, peopleNav,
    nextPrevBtns, sebas, guille, roli, ceoButton, cfoButton, finDir, overlay, text1, text2, text3, img1, img2,
    prev, next, dotsArr, dot1, dot2, dot3, main, navLinks
}


